// Build script for `excalidraw-image-fonts-cjk-extra`.
//
// Walks the crate's `fonts/` directory for `*.ttf.br` files (brotli-compressed
// TTF) and emits `OUT_DIR/fonts.rs` declaring a sorted-by-relative-path
// `pub static FONTS: &[(&str, &[u8])]` table. Each entry's bytes are baked
// in via `include_bytes!` against `CARGO_MANIFEST_DIR/fonts/...`.
//
// The FONTS key uses the original `.woff2` extension (for URL-matching in
// fetch-fonts.mjs) even though the physical file is `.ttf.br`. The consumer
// (`excalidraw-image`) decompresses brotli at build/run time.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let fonts_dir = manifest.join("fonts");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    let mut paths = Vec::new();
    walk(&fonts_dir, &fonts_dir, &mut paths);
    paths.sort();

    // The fonts/ directory is .gitignored and populated by
    // `npm run sync-fonts` from node_modules/@excalidraw/excalidraw.
    // If it's empty we surface a friendly error rather than emitting a
    // silently-empty FONTS array (which downstream would then fail in
    // a less helpful way).
    if paths.is_empty() {
        panic!(
            "{}/fonts/ contains no .ttf.br files. Run \
             `npm ci && npm run sync-fonts` (or `make bootstrap`) \
             before building.",
            manifest.display(),
        );
    }

    let mut body = String::new();
    body.push_str("// Generated by build.rs. Do not edit.\n");
    body.push_str("pub static FONTS: &[(&str, &[u8])] = &[\n");
    for disk_rel in &paths {
        let disk_posix = disk_rel.replace('\\', "/");
        let key = disk_posix
            .strip_suffix(".ttf.br")
            .map(|stem| format!("{stem}.woff2"))
            .unwrap_or_else(|| disk_posix.clone());
        body.push_str(&format!(
            "    (\"{key}\", include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/fonts/{disk_posix}\"))),\n",
        ));
    }
    body.push_str("];\n");

    let dest = out_dir.join("fonts.rs");
    fs::write(&dest, body).expect("failed to write fonts.rs");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", fonts_dir.display());
    for rel in &paths {
        println!(
            "cargo:rerun-if-changed={}",
            fonts_dir.join(rel).display()
        );
    }
}

fn walk(root: &Path, dir: &Path, out: &mut Vec<String>) {
    let entries = match fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return,
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let ft = match entry.file_type() {
            Ok(t) => t,
            Err(_) => continue,
        };
        if ft.is_dir() {
            walk(root, &path, out);
        } else if ft.is_file()
            && path
                .file_name()
                .and_then(|s| s.to_str())
                .map_or(false, |s| s.ends_with(".ttf.br"))
        {
            let rel = path
                .strip_prefix(root)
                .expect("walked path is under root")
                .to_string_lossy()
                .to_string();
            out.push(rel);
        }
    }
}
